### ISSUE TITLE
Library Error

### ISSUE THREAD

**Issue by 641i130** [TheMohawkNinja/WallFade#2]
I've installed the newest version of ImageMagick, but it gives me odd errors about missing `.so` files.
```WallFade: error while loading shared libraries: libMagick++-7.Q16HDRI.so.4: cannot open shared object file: No such file or directory```

**Comment by TheMohawkNinja** [comment]
@641i130 I believe I've seen that error when a new version of Magick++ is installed. Did you compile the program with the g++ command posted at the bottom of the README.md file, or did you just run the pre-compiled .exe?

**Comment by 641i130** [comment]
OH I just had to compile it. It works now lol
